package com.miwo.model;

public class ArticlePic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_pic.id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_pic.article_id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    private Long articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_pic.pic_id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    private Long picId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_pic.id
     *
     * @return the value of article_pic.id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_pic.id
     *
     * @param id the value for article_pic.id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_pic.article_id
     *
     * @return the value of article_pic.article_id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_pic.article_id
     *
     * @param articleId the value for article_pic.article_id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_pic.pic_id
     *
     * @return the value of article_pic.pic_id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public Long getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_pic.pic_id
     *
     * @param picId the value for article_pic.pic_id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public void setPicId(Long picId) {
        this.picId = picId;
    }
}