package com.miwo.model;

import java.util.ArrayList;
import java.util.List;

public class InheritExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inherit
     *
     * @mbg.generated Wed Apr 25 10:19:05 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inherit
     *
     * @mbg.generated Wed Apr 25 10:19:05 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inherit
     *
     * @mbg.generated Wed Apr 25 10:19:05 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inherit
     *
     * @mbg.generated Wed Apr 25 10:19:05 CST 2018
     */
    public InheritExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inherit
     *
     * @mbg.generated Wed Apr 25 10:19:05 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inherit
     *
     * @mbg.generated Wed Apr 25 10:19:05 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inherit
     *
     * @mbg.generated Wed Apr 25 10:19:05 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inherit
     *
     * @mbg.generated Wed Apr 25 10:19:05 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inherit
     *
     * @mbg.generated Wed Apr 25 10:19:05 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inherit
     *
     * @mbg.generated Wed Apr 25 10:19:05 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inherit
     *
     * @mbg.generated Wed Apr 25 10:19:05 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inherit
     *
     * @mbg.generated Wed Apr 25 10:19:05 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inherit
     *
     * @mbg.generated Wed Apr 25 10:19:05 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inherit
     *
     * @mbg.generated Wed Apr 25 10:19:05 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inherit
     *
     * @mbg.generated Wed Apr 25 10:19:05 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFatherTypeIsNull() {
            addCriterion("father_type is null");
            return (Criteria) this;
        }

        public Criteria andFatherTypeIsNotNull() {
            addCriterion("father_type is not null");
            return (Criteria) this;
        }

        public Criteria andFatherTypeEqualTo(String value) {
            addCriterion("father_type =", value, "fatherType");
            return (Criteria) this;
        }

        public Criteria andFatherTypeNotEqualTo(String value) {
            addCriterion("father_type <>", value, "fatherType");
            return (Criteria) this;
        }

        public Criteria andFatherTypeGreaterThan(String value) {
            addCriterion("father_type >", value, "fatherType");
            return (Criteria) this;
        }

        public Criteria andFatherTypeGreaterThanOrEqualTo(String value) {
            addCriterion("father_type >=", value, "fatherType");
            return (Criteria) this;
        }

        public Criteria andFatherTypeLessThan(String value) {
            addCriterion("father_type <", value, "fatherType");
            return (Criteria) this;
        }

        public Criteria andFatherTypeLessThanOrEqualTo(String value) {
            addCriterion("father_type <=", value, "fatherType");
            return (Criteria) this;
        }

        public Criteria andFatherTypeLike(String value) {
            addCriterion("father_type like", value, "fatherType");
            return (Criteria) this;
        }

        public Criteria andFatherTypeNotLike(String value) {
            addCriterion("father_type not like", value, "fatherType");
            return (Criteria) this;
        }

        public Criteria andFatherTypeIn(List<String> values) {
            addCriterion("father_type in", values, "fatherType");
            return (Criteria) this;
        }

        public Criteria andFatherTypeNotIn(List<String> values) {
            addCriterion("father_type not in", values, "fatherType");
            return (Criteria) this;
        }

        public Criteria andFatherTypeBetween(String value1, String value2) {
            addCriterion("father_type between", value1, value2, "fatherType");
            return (Criteria) this;
        }

        public Criteria andFatherTypeNotBetween(String value1, String value2) {
            addCriterion("father_type not between", value1, value2, "fatherType");
            return (Criteria) this;
        }

        public Criteria andMotherTypeIsNull() {
            addCriterion("mother_type is null");
            return (Criteria) this;
        }

        public Criteria andMotherTypeIsNotNull() {
            addCriterion("mother_type is not null");
            return (Criteria) this;
        }

        public Criteria andMotherTypeEqualTo(String value) {
            addCriterion("mother_type =", value, "motherType");
            return (Criteria) this;
        }

        public Criteria andMotherTypeNotEqualTo(String value) {
            addCriterion("mother_type <>", value, "motherType");
            return (Criteria) this;
        }

        public Criteria andMotherTypeGreaterThan(String value) {
            addCriterion("mother_type >", value, "motherType");
            return (Criteria) this;
        }

        public Criteria andMotherTypeGreaterThanOrEqualTo(String value) {
            addCriterion("mother_type >=", value, "motherType");
            return (Criteria) this;
        }

        public Criteria andMotherTypeLessThan(String value) {
            addCriterion("mother_type <", value, "motherType");
            return (Criteria) this;
        }

        public Criteria andMotherTypeLessThanOrEqualTo(String value) {
            addCriterion("mother_type <=", value, "motherType");
            return (Criteria) this;
        }

        public Criteria andMotherTypeLike(String value) {
            addCriterion("mother_type like", value, "motherType");
            return (Criteria) this;
        }

        public Criteria andMotherTypeNotLike(String value) {
            addCriterion("mother_type not like", value, "motherType");
            return (Criteria) this;
        }

        public Criteria andMotherTypeIn(List<String> values) {
            addCriterion("mother_type in", values, "motherType");
            return (Criteria) this;
        }

        public Criteria andMotherTypeNotIn(List<String> values) {
            addCriterion("mother_type not in", values, "motherType");
            return (Criteria) this;
        }

        public Criteria andMotherTypeBetween(String value1, String value2) {
            addCriterion("mother_type between", value1, value2, "motherType");
            return (Criteria) this;
        }

        public Criteria andMotherTypeNotBetween(String value1, String value2) {
            addCriterion("mother_type not between", value1, value2, "motherType");
            return (Criteria) this;
        }

        public Criteria andChildTypeIsNull() {
            addCriterion("child_type is null");
            return (Criteria) this;
        }

        public Criteria andChildTypeIsNotNull() {
            addCriterion("child_type is not null");
            return (Criteria) this;
        }

        public Criteria andChildTypeEqualTo(String value) {
            addCriterion("child_type =", value, "childType");
            return (Criteria) this;
        }

        public Criteria andChildTypeNotEqualTo(String value) {
            addCriterion("child_type <>", value, "childType");
            return (Criteria) this;
        }

        public Criteria andChildTypeGreaterThan(String value) {
            addCriterion("child_type >", value, "childType");
            return (Criteria) this;
        }

        public Criteria andChildTypeGreaterThanOrEqualTo(String value) {
            addCriterion("child_type >=", value, "childType");
            return (Criteria) this;
        }

        public Criteria andChildTypeLessThan(String value) {
            addCriterion("child_type <", value, "childType");
            return (Criteria) this;
        }

        public Criteria andChildTypeLessThanOrEqualTo(String value) {
            addCriterion("child_type <=", value, "childType");
            return (Criteria) this;
        }

        public Criteria andChildTypeLike(String value) {
            addCriterion("child_type like", value, "childType");
            return (Criteria) this;
        }

        public Criteria andChildTypeNotLike(String value) {
            addCriterion("child_type not like", value, "childType");
            return (Criteria) this;
        }

        public Criteria andChildTypeIn(List<String> values) {
            addCriterion("child_type in", values, "childType");
            return (Criteria) this;
        }

        public Criteria andChildTypeNotIn(List<String> values) {
            addCriterion("child_type not in", values, "childType");
            return (Criteria) this;
        }

        public Criteria andChildTypeBetween(String value1, String value2) {
            addCriterion("child_type between", value1, value2, "childType");
            return (Criteria) this;
        }

        public Criteria andChildTypeNotBetween(String value1, String value2) {
            addCriterion("child_type not between", value1, value2, "childType");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inherit
     *
     * @mbg.generated do_not_delete_during_merge Wed Apr 25 10:19:05 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inherit
     *
     * @mbg.generated Wed Apr 25 10:19:05 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}