package com.miwo.model;

public class MyMap {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.map_id
     *
     * @mbg.generated Mon May 07 10:58:05 CST 2018
     */
    private Long mapId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.user_id
     *
     * @mbg.generated Mon May 07 10:58:05 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.latitude
     *
     * @mbg.generated Mon May 07 10:58:05 CST 2018
     */
    private Double latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.longitude
     *
     * @mbg.generated Mon May 07 10:58:05 CST 2018
     */
    private Double longitude;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.map_id
     *
     * @return the value of map.map_id
     *
     * @mbg.generated Mon May 07 10:58:05 CST 2018
     */
    public Long getMapId() {
        return mapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.map_id
     *
     * @param mapId the value for map.map_id
     *
     * @mbg.generated Mon May 07 10:58:05 CST 2018
     */
    public void setMapId(Long mapId) {
        this.mapId = mapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.user_id
     *
     * @return the value of map.user_id
     *
     * @mbg.generated Mon May 07 10:58:05 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.user_id
     *
     * @param userId the value for map.user_id
     *
     * @mbg.generated Mon May 07 10:58:05 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.latitude
     *
     * @return the value of map.latitude
     *
     * @mbg.generated Mon May 07 10:58:05 CST 2018
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.latitude
     *
     * @param latitude the value for map.latitude
     *
     * @mbg.generated Mon May 07 10:58:05 CST 2018
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.longitude
     *
     * @return the value of map.longitude
     *
     * @mbg.generated Mon May 07 10:58:05 CST 2018
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.longitude
     *
     * @param longitude the value for map.longitude
     *
     * @mbg.generated Mon May 07 10:58:05 CST 2018
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }
}