package com.miwo.model;

public class Notice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.notice_id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    private Long noticeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.notice_test
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    private String noticeTest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.article_id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    private Long articleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.notice_id
     *
     * @return the value of notice.notice_id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public Long getNoticeId() {
        return noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.notice_id
     *
     * @param noticeId the value for notice.notice_id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public void setNoticeId(Long noticeId) {
        this.noticeId = noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.notice_test
     *
     * @return the value of notice.notice_test
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public String getNoticeTest() {
        return noticeTest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.notice_test
     *
     * @param noticeTest the value for notice.notice_test
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public void setNoticeTest(String noticeTest) {
        this.noticeTest = noticeTest == null ? null : noticeTest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.article_id
     *
     * @return the value of notice.article_id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.article_id
     *
     * @param articleId the value for notice.article_id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }
}