package com.miwo.model;

import java.util.Date;

public class Pic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic.pic_id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    private Long picId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic.pic_name
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    private String picName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic.pic_path
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    private String picPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic.pic_url
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pic.add_time
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic.pic_id
     *
     * @return the value of pic.pic_id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public Long getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic.pic_id
     *
     * @param picId the value for pic.pic_id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public void setPicId(Long picId) {
        this.picId = picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic.pic_name
     *
     * @return the value of pic.pic_name
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public String getPicName() {
        return picName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic.pic_name
     *
     * @param picName the value for pic.pic_name
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public void setPicName(String picName) {
        this.picName = picName == null ? null : picName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic.pic_path
     *
     * @return the value of pic.pic_path
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public String getPicPath() {
        return picPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic.pic_path
     *
     * @param picPath the value for pic.pic_path
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public void setPicPath(String picPath) {
        this.picPath = picPath == null ? null : picPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic.pic_url
     *
     * @return the value of pic.pic_url
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic.pic_url
     *
     * @param picUrl the value for pic.pic_url
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pic.add_time
     *
     * @return the value of pic.add_time
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pic.add_time
     *
     * @param addTime the value for pic.add_time
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }
}