package com.miwo.model;

public class Sale {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.sale_id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    private Long saleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.article_id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    private Long articleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.sale_id
     *
     * @return the value of sale.sale_id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public Long getSaleId() {
        return saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.sale_id
     *
     * @param saleId the value for sale.sale_id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public void setSaleId(Long saleId) {
        this.saleId = saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.article_id
     *
     * @return the value of sale.article_id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.article_id
     *
     * @param articleId the value for sale.article_id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }
}