package com.miwo.model;

public class Takeaway {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column takeaway.takeaway_id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    private Long takeawayId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column takeaway.article_id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    private Long articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column takeaway.user_id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column takeaway.takeaway_id
     *
     * @return the value of takeaway.takeaway_id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public Long getTakeawayId() {
        return takeawayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column takeaway.takeaway_id
     *
     * @param takeawayId the value for takeaway.takeaway_id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public void setTakeawayId(Long takeawayId) {
        this.takeawayId = takeawayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column takeaway.article_id
     *
     * @return the value of takeaway.article_id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column takeaway.article_id
     *
     * @param articleId the value for takeaway.article_id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column takeaway.user_id
     *
     * @return the value of takeaway.user_id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column takeaway.user_id
     *
     * @param userId the value for takeaway.user_id
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}