package com.miwo.dao;

import com.miwo.model.Advice;
import com.miwo.model.AdviceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbg.generated Thu May 03 13:55:30 CST 2018
     */
    long countByExample(AdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbg.generated Thu May 03 13:55:30 CST 2018
     */
    int deleteByExample(AdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbg.generated Thu May 03 13:55:30 CST 2018
     */
    int deleteByPrimaryKey(Long adviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbg.generated Thu May 03 13:55:30 CST 2018
     */
    int insert(Advice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbg.generated Thu May 03 13:55:30 CST 2018
     */
    int insertSelective(Advice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbg.generated Thu May 03 13:55:30 CST 2018
     */
    List<Advice> selectByExample(AdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbg.generated Thu May 03 13:55:30 CST 2018
     */
    Advice selectByPrimaryKey(Long adviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbg.generated Thu May 03 13:55:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") Advice record, @Param("example") AdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbg.generated Thu May 03 13:55:30 CST 2018
     */
    int updateByExample(@Param("record") Advice record, @Param("example") AdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbg.generated Thu May 03 13:55:30 CST 2018
     */
    int updateByPrimaryKeySelective(Advice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbg.generated Thu May 03 13:55:30 CST 2018
     */
    int updateByPrimaryKey(Advice record);
}