package com.miwo.dao;

import com.miwo.model.ArticlePic;
import com.miwo.model.ArticlePicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticlePicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_pic
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    long countByExample(ArticlePicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_pic
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    int deleteByExample(ArticlePicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_pic
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_pic
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    int insert(ArticlePic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_pic
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    int insertSelective(ArticlePic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_pic
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    List<ArticlePic> selectByExample(ArticlePicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_pic
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    ArticlePic selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_pic
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") ArticlePic record, @Param("example") ArticlePicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_pic
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    int updateByExample(@Param("record") ArticlePic record, @Param("example") ArticlePicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_pic
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    int updateByPrimaryKeySelective(ArticlePic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_pic
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    int updateByPrimaryKey(ArticlePic record);
}