package com.miwo.dao;

import com.miwo.model.MyMap;
import com.miwo.model.MyMapExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MyMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated Mon May 07 10:58:05 CST 2018
     */
    long countByExample(MyMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated Mon May 07 10:58:05 CST 2018
     */
    int deleteByExample(MyMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated Mon May 07 10:58:05 CST 2018
     */
    int deleteByPrimaryKey(Long mapId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated Mon May 07 10:58:05 CST 2018
     */
    int insert(MyMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated Mon May 07 10:58:05 CST 2018
     */
    int insertSelective(MyMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated Mon May 07 10:58:05 CST 2018
     */
    List<MyMap> selectByExample(MyMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated Mon May 07 10:58:05 CST 2018
     */
    MyMap selectByPrimaryKey(Long mapId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated Mon May 07 10:58:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") MyMap record, @Param("example") MyMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated Mon May 07 10:58:05 CST 2018
     */
    int updateByExample(@Param("record") MyMap record, @Param("example") MyMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated Mon May 07 10:58:05 CST 2018
     */
    int updateByPrimaryKeySelective(MyMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated Mon May 07 10:58:05 CST 2018
     */
    int updateByPrimaryKey(MyMap record);
}