package com.miwo.dao;

import com.miwo.model.Pic;
import com.miwo.model.PicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    long countByExample(PicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    int deleteByExample(PicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    int deleteByPrimaryKey(Long picId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    int insert(Pic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    int insertSelective(Pic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    List<Pic> selectByExample(PicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    Pic selectByPrimaryKey(Long picId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") Pic record, @Param("example") PicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    int updateByExample(@Param("record") Pic record, @Param("example") PicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    int updateByPrimaryKeySelective(Pic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pic
     *
     * @mbg.generated Fri Apr 27 16:30:54 CST 2018
     */
    int updateByPrimaryKey(Pic record);
}