package com.miwo.vo;

import java.util.List;

public class InheritVo {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column inherit.id
	 *
	 * @mbg.generated Wed Apr 25 10:19:05 CST 2018
	 */
	private Long id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column inherit.father_type
	 *
	 * @mbg.generated Wed Apr 25 10:19:05 CST 2018
	 */
	private String fatherType;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column inherit.mother_type
	 *
	 * @mbg.generated Wed Apr 25 10:19:05 CST 2018
	 */
	private String motherType;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column inherit.child_type
	 *
	 * @mbg.generated Wed Apr 25 10:19:05 CST 2018
	 */
	private List<String> children;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getFatherType() {
		return fatherType;
	}

	public void setFatherType(String fatherType) {
		this.fatherType = fatherType;
	}

	public String getMotherType() {
		return motherType;
	}

	public void setMotherType(String motherType) {
		this.motherType = motherType;
	}

	public List<String> getChildren() {
		return children;
	}

	public void setChildren(List<String> children) {
		this.children = children;
	}

	public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column inherit.user_id
	 *
	 * @mbg.generated Wed Apr 25 10:19:05 CST 2018
	 */
	private Long userId;
}
